# Stage 1: Build the application
FROM maven:3.8.5-openjdk-21 AS build
WORKDIR /app
COPY backend/pom.xml .
RUN mvn dependency:go-offline
COPY backend/. .
RUN mvn package -DskipTests

# Stage 2: Create the final image
FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
